### ISSUE TITLE
Define a Data Structure Model on Firebase

### ISSUE THREAD

**Issue by danielindiano** [meumobi/AMS.Report#4]
Define wich data structure we'll use to store the reports on firebase.

We can use:

#### Simple data on /reports
![screenshot from 2017-03-23 15-24-00](https://cloud.githubusercontent.com/assets/553232/24263901/592fb1ea-0fdd-11e7-9cf1-e9220601f1b6.png)

#### Insert a new level for date /reports/<date>
![screenshot from 2017-03-23 15-23-06](https://cloud.githubusercontent.com/assets/553232/24263879/47af89d6-0fdd-11e7-8cc4-19fd0d74e1d6.png)
#### Insert a new level for provider /reports/<provider>
![screenshot from 2017-03-23 15-26-21](https://cloud.githubusercontent.com/assets/553232/24263853/32f3e406-0fdd-11e7-938f-948608ff10bc.png)

#### Another suggestion?

**Comment by vdias38** [comment]
Because we can’t query on multiple fields we should structure our json tree as /reports/:site

![ams_report_ _realtime_database_ _firebase_console](https://cloud.githubusercontent.com/assets/9011612/26362319/d920140a-3fdd-11e7-9f79-c306c4a9ca55.png)


> Queries can only order by one key at a time

source: https://firebase.google.com/docs/database/admin/retrieve-data

It should allow to call site on URL and filter results by start_date and end_date

```
    if (this.site) {
      query.orderByChild = 'date';
      query.startAt = "2017-03-02";
      query.endAt = "2017-03-04";
    }
    
    this.reports = db.list('/reports/' + this.site.title, {query: query});
```
